### ISSUE TITLE
无法运行在Flutter2.5版本

### ISSUE THREAD

**Issue by shirne** [arcticfox1919/flutter_easy_permission#2]
通过报错查到是
MethodChannel.checkMethodCallHandler 在flutter2.5中被移除了（移到了测试包中）

参考
https://github.com/flutter/flutter/blob/2.5.1/packages/flutter/lib/src/services/platform_channel.dart
第400行

**Comment by arcticfox1919** [comment]
升级到 `flutter_easy_permission: ^1.1.1`
